"""Head registry — turns a profile id from the registry into a launch command.

A worker/reviewer head is data (`[resources.*]` the accounts/limits heads draw from,
`[profiles.*]` the runtime+model+resource+fallback-chain combos, `[role_defaults]` which head each
role runs on), not a hardcoded `claude` invocation. `render_command` picks a profile's adapter
(ADAPTERS below) and builds the shell command the dispatcher hands to `orca terminal create`. A
new head is a new `[profiles.<id>]` entry plus, only if its launch shape is genuinely new, one
more `_render_*` function here — no caller changes.

Which heads exist is installation configuration, not product code: the accounts, models and
fallback chains one host pays for are not the ones another host has. So an installation that has
been upgraded reads its own `<instance>/heads/heads.yaml` snapshot, generated by `secretary
upgrade` from whichever canon that installation owns. The `heads.toml` shipped here is the
portable default a checkout with no installation behind it falls back to. Both go through the same
validator, so a role default or fallback chain that names a head nobody defined is rejected the
same way wherever it came from.

Pure and I/O-light (`load_registry` caches its read per process — see its docstring): no
Kanboard, no orca, no subprocess.
"""
from __future__ import annotations

import json
import os
import shlex
import tomllib
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import yaml

from ...runtime import role_env

HEADS_TOML = Path(__file__).with_name("heads.toml")
# The installation whose registry this process runs off, and where that registry sits inside it.
# Only an explicitly configured instance counts: a checkout on a host that happens to have an
# installation must keep reading the product default, or every test about the shipped registry
# would silently assert against the developer's own heads.
INSTANCE_ENV = "SECRETARY_INSTANCE"
INSTANCE_SNAPSHOT_RELATIVE = Path("heads") / "heads.yaml"
# Point one process at another registry without moving its installation. Tests use it; so does an
# operator diffing a candidate registry against the live one.
REGISTRY_ENV = "TA_HEADS_REGISTRY"


def installed_registry_path() -> Path | None:
    """The configured installation's own snapshot, or None when there is no installation here.

    Whether that snapshot exists is deliberately not asked. Selecting an installation is the
    operator's decision about which generation this process runs off; a missing, unreadable or
    dangling snapshot under it is a broken installation, and the load below then fails by that
    path. Answering "no installation" instead would route a selected non-default instance off a
    mutable product checkout, which is the one thing the snapshot exists to prevent.
    """
    configured = os.environ.get(INSTANCE_ENV)
    if not configured:
        return None
    base = Path(configured).expanduser()
    if base.name == "instance.yaml":
        base = base.parent
    return base / INSTANCE_SNAPSHOT_RELATIVE


def registry_path() -> Path:
    """The registry this process reads: the installation's own snapshot, else the product default.

    The product default is for a checkout with no installation selected at all, not for a selected
    installation whose snapshot is unusable.

    Resolved per call rather than at import, so pointing a process at another installation through
    ``SECRETARY_INSTANCE`` moves the registry without reloading the module.
    """
    override = os.environ.get(REGISTRY_ENV)
    if override:
        return Path(override).expanduser()
    return installed_registry_path() or HEADS_TOML

# The CODEX_HOME shared by Orca-managed Codex sessions and pipeline heads. One physical home keeps
# auth refresh, MCP, skills, hooks, and quota probes on the same state. Pinned explicitly because
# the health probe is a plain subprocess rather than an Orca terminal. Env-overridable so tests can
# use a throwaway home.
CODEX_HOME = os.environ.get(
    "TA_CODEX_HOME", str(Path.home() / ".config" / "orca" / "codex-runtime-home" / "home")
)

# Last-resort profile ids, used only when the selected registry routes a role nowhere. Which head a
# role actually runs on is `[role_defaults]` in that registry; these keep a tick launching something
# rather than nothing when it has been stripped out.
DEFAULT_PROFILE = "codex"
REVIEWER_PROFILE = "codex-reviewer"

CODEX_EFFORTS = {
    "default": None,
    "low": "low",
    "medium": "medium",
    "high": "high",
    "extra": "xhigh",
    "xhigh": "xhigh",
    "max": "max",
    "ultra": "ultra",
}

CODEX_LAUNCH_MODES = {"exec", "tui"}


@dataclass(frozen=True)
class LaunchSpec:
    """A terminal create command plus an optional prompt delivered after the TUI is ready."""

    command: str
    initial_prompt: str | None = None
    terminal_kind: str | None = None


class HeadRegistryError(RuntimeError):
    """heads.toml is missing/malformed, or a profile/resource/adapter/fallback it names is unknown."""


def _render_claude(profile: dict, *, prompt: str) -> str:
    model = profile.get("model")
    model_flag = f" --model {model}" if model else ""
    return f"claude --dangerously-skip-permissions{model_flag} {prompt!r}"


def _render_hermes(profile: dict, *, prompt: str) -> str:
    """Hermes' one-shot-seeded-session equivalent of `claude --dangerously-skip-permissions
    <prompt>`: `-z` seeds an autonomous session with the initial message (not `-q`/`chat`'s
    single-turn query mode), `--yolo` is Hermes' skip-permissions, `--cli` forces the plain REPL
    (no TUI) so it behaves in an Orca terminal the same way the classic `claude` invocation does."""
    parts = ["hermes", "-z", repr(prompt)]
    if profile.get("model"):
        parts += ["-m", profile["model"]]
    if profile.get("provider"):
        parts += ["--provider", profile["provider"]]
    parts += ["--yolo", "--cli"]
    return " ".join(parts)


def _render_codex(profile: dict, *, prompt: str) -> str:
    """Codex' non-interactive equivalent of `claude --dangerously-skip-permissions <prompt>`:
    `exec` runs one-shot (prints the agent turn, no TUI), `--dangerously-bypass-approvals-and-sandbox`
    is codex' skip-permissions (the Orca worktree is the external sandbox; it also lets the memory
    MCP tool run without an interactive approval prompt), `--skip-git-repo-check` keeps a
    not-yet-a-repo workspace from aborting. `CODEX_HOME` is pinned to the ChatGPT-authed home
    (see CODEX_HOME above) so the head finds its login, memory MCP, and global AGENTS.md regardless
    of the launching terminal's env. `codex_home` on the profile overrides it (e.g. for an e2e)."""
    home = profile.get("codex_home") or CODEX_HOME
    model = profile.get("model")
    model_flag = f" -m {model}" if model else ""
    effort = CODEX_EFFORTS.get(profile.get("effort", "default"))
    effort_flag = ""
    if effort:
        effort_flag = " -c " + shlex.quote(f'model_reasoning_effort="{effort}"')
    return (f"CODEX_HOME={home} codex exec --dangerously-bypass-approvals-and-sandbox "
            f"--skip-git-repo-check{model_flag}{effort_flag} {prompt!r}")


def _toml_basic_string(value: str) -> str:
    return json.dumps(value)


def _resolve_git_path(value: str, base: Path) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = base / path
    return path.resolve(strict=False)


def _workspace_git_dir(workspace_path: Path) -> Path | None:
    dotgit = workspace_path / ".git"
    try:
        if dotgit.is_dir():
            return dotgit.resolve(strict=False)
        if dotgit.is_file():
            line = dotgit.read_text(encoding="utf-8").splitlines()[0].strip()
    except (OSError, IndexError):
        return None
    if not dotgit.is_file():
        return None
    if not line.startswith("gitdir:"):
        return None
    return _resolve_git_path(line.split(":", 1)[1].strip(), workspace_path)


def _git_common_dir(git_dir: Path) -> Path:
    common = git_dir / "commondir"
    try:
        if common.is_file():
            value = common.read_text(encoding="utf-8").splitlines()[0].strip()
            if value:
                return _resolve_git_path(value, git_dir)
    except (OSError, IndexError):
        pass
    return git_dir.resolve(strict=False)


def _codex_repository_trust_root(workspace_path: Path) -> Path | None:
    """Codex' TUI trust check keys linked worktrees by the common git dir's repo root."""
    git_dir = _workspace_git_dir(workspace_path)
    if git_dir is None:
        return None
    common_dir = _git_common_dir(git_dir)
    if common_dir.name != ".git":
        return None
    if git_dir != common_dir and not git_dir.is_relative_to(common_dir / "worktrees"):
        return None
    return common_dir.parent.resolve(strict=False)


def _codex_tui_trust_paths(workspace: str) -> list[str]:
    workspace_path = Path(workspace).resolve(strict=False)
    paths = [workspace_path]
    repo_root = _codex_repository_trust_root(workspace_path)
    if repo_root is not None:
        paths.append(repo_root)
    seen = set()
    out = []
    for path in paths:
        key = str(path)
        if key not in seen:
            seen.add(key)
            out.append(key)
    return out


def _codex_trust_flag(path: str) -> str:
    key = f"projects.{_toml_basic_string(path)}.trust_level=\"trusted\""
    return " -c " + shlex.quote(key)


def _render_codex_tui(profile: dict, *, workspace: str | None = None) -> str:
    """Interactive Codex TUI command. The prompt is sent after Orca reports `tui-idle`.

    `--skip-git-repo-check` is an `exec`-only flag in Codex 0.143; the top-level TUI rejects it.
    Pipeline worker/reviewer workspaces are git worktrees already, so the TUI path does not need
    it. Trust overrides only skip Codex' directory-trust dialog for the provisioned worktree and,
    for linked worktrees, the same repository root Codex derives from the common git dir. The head
    already runs with `--dangerously-bypass-approvals-and-sandbox`, so this does not grant extra
    rights.
    """
    home = profile.get("codex_home") or CODEX_HOME
    model = profile.get("model")
    model_flag = f" -m {model}" if model else ""
    effort = CODEX_EFFORTS.get(profile.get("effort", "default"))
    effort_flag = ""
    if effort:
        effort_flag = " -c " + shlex.quote(f'model_reasoning_effort="{effort}"')
    if not workspace:
        raise HeadRegistryError("codex TUI launch requires workspace for directory trust override")
    trust_flags = "".join(_codex_trust_flag(path) for path in _codex_tui_trust_paths(workspace))
    return (f"CODEX_HOME={home} codex --dangerously-bypass-approvals-and-sandbox"
            f"{model_flag}{effort_flag}{trust_flags}")


def _env_codex_mode() -> str | None:
    mode = os.environ.get("TA_CODEX_MODE")
    if mode:
        mode = mode.strip().lower()
        if mode not in CODEX_LAUNCH_MODES:
            known = ", ".join(sorted(CODEX_LAUNCH_MODES))
            raise HeadRegistryError(f"unknown TA_CODEX_MODE {mode!r} (known: {known})")
        return mode
    flag = os.environ.get("TA_CODEX_TUI")
    if flag is None:
        return None
    flag = flag.strip().lower()
    if flag in {"", "0", "false", "no", "off"}:
        return "exec"
    return "tui"


def _codex_launch_mode(profile: dict) -> str:
    return _env_codex_mode() or profile.get("codex_mode", "exec")


ADAPTERS = {
    "claude": _render_claude,
    "hermes": _render_hermes,
    "codex": _render_codex,
}


class Registry:
    def __init__(self, resources: dict, profiles: dict, role_defaults: dict | None = None):
        self.resources = resources
        self.profiles = profiles
        self.role_defaults = role_defaults or {}

    def role_default(self, role: str) -> str | None:
        """The head this registry routes `role` to, or None when it routes it nowhere.

        Role routing is registry data for every role that has one — worker, reviewer, observer and
        the background agents alike — so a caller never has to carry a second opinion about which
        head a role runs on.
        """
        head = self.role_defaults.get(role)
        return str(head) if head else None

    def profile(self, profile_id: str) -> dict:
        """The profile dict for `profile_id`, or HeadRegistryError with the known ids — the text
        a claim guard or a create/update validation surfaces verbatim to whoever reads it."""
        prof = self.profiles.get(profile_id)
        if prof is None:
            known = ", ".join(sorted(self.profiles)) or "(none)"
            raise HeadRegistryError(f"unknown head {profile_id!r} (known: {known})")
        return prof

    def known(self) -> list[str]:
        return sorted(self.profiles)


def role_head(role: str, fallback: str, registry: Registry | None = None) -> str:
    """The head the selected registry routes `role` to, or `fallback` when it routes it nowhere.

    Best-effort by design: an unreadable registry must not leave a role with no head to launch at
    all. The caller that then tries to render `fallback` raises the same registry error anyway, so
    nothing is swallowed — it is just raised at the point where it actually blocks something.
    """
    try:
        reg = registry or load_registry()
    except HeadRegistryError:
        return fallback
    return reg.role_default(role) or fallback


def default_head(registry: Registry | None = None) -> str:
    """The head a card that names none of its own runs on."""
    return role_head("new_card", DEFAULT_PROFILE, registry)


def reviewer_head(registry: Registry | None = None) -> str:
    """The head a card that names no reviewer of its own is reviewed by.

    ``TA_REVIEWER_HEAD`` still wins: it is the one-tick override an operator sets to try a
    reviewer without editing the installation's registry.
    """
    override = os.environ.get("TA_REVIEWER_HEAD")
    if override:
        return override
    return role_head("reviewer", REVIEWER_PROFILE, registry)


def profile_info(profile_id: str, registry: Registry | None = None) -> dict:
    """Display-facing profile facts. Unknown profiles return a marked record instead of raising.

    `effort` is Codex-specific in the current registry. Non-Codex adapters deliberately show
    `n/a` rather than an empty string, so board/list consumers never have to special-case a blank
    label.
    """
    reg = registry or load_registry()
    try:
        prof = reg.profile(profile_id)
    except HeadRegistryError:
        return {
            "profile": profile_id,
            "known": False,
            "adapter": "unknown",
            "model": "unknown",
            "effort": "unknown",
        }
    adapter = prof.get("adapter") or "unknown"
    effort = prof.get("effort", "default") if adapter == "codex" else "n/a"
    return {
        "profile": profile_id,
        "known": True,
        "adapter": adapter,
        "model": prof.get("model") or "default",
        "effort": effort,
    }


def _named(value: object, what: str) -> str:
    """A registry field that has to be a plain name before anything can be looked up by it.

    Checked before the membership tests below rather than left to them: a list where a name
    belongs is unhashable, so `value not in table` would raise TypeError past every caller that
    only knows how to handle HeadRegistryError.
    """
    if not isinstance(value, str):
        raise HeadRegistryError(f"{what} must be a name, got {type(value).__name__}")
    return value


def validate_registry(resources: dict, profiles: dict) -> None:
    """Structural check every consumer of the registry shares: the product canon at load time and
    the installation snapshot the dispatcher runs off.

    Shapes are checked alongside names. A registry is hand-written TOML or a snapshot generated
    from one, so an entry can be any type its author typed; every malformed one has to come back
    as a HeadRegistryError here rather than as an AttributeError or a TypeError somewhere down in
    a consumer that assumed a mapping.
    """
    if not isinstance(resources, dict):
        raise HeadRegistryError(f"[resources] must be a table, got {type(resources).__name__}")
    if not isinstance(profiles, dict):
        raise HeadRegistryError(f"[profiles] must be a table, got {type(profiles).__name__}")
    for rid, res in resources.items():
        if not isinstance(res, dict):
            raise HeadRegistryError(f"resource {rid!r} must be a table, got {type(res).__name__}")
    for pid, prof in profiles.items():
        if not isinstance(prof, dict):
            raise HeadRegistryError(f"profile {pid!r} must be a table, got {type(prof).__name__}")
        resource = _named(prof.get("resource"), f"profile {pid!r} resource")
        if resource not in resources:
            raise HeadRegistryError(f"profile {pid!r} references unknown resource {resource!r}")
        adapter = _named(prof.get("adapter"), f"profile {pid!r} adapter")
        if adapter not in ADAPTERS:
            raise HeadRegistryError(f"profile {pid!r} has unknown adapter {adapter!r} "
                                    f"(known: {', '.join(sorted(ADAPTERS))})")
        if adapter == "codex":
            effort = _named(prof.get("effort", "default"), f"profile {pid!r} effort")
            if effort not in CODEX_EFFORTS:
                known = ", ".join(sorted(CODEX_EFFORTS))
                raise HeadRegistryError(f"profile {pid!r} has unknown codex effort {effort!r} "
                                        f"(known: {known})")
            mode = _named(prof.get("codex_mode", "exec"), f"profile {pid!r} codex launch mode")
            if mode not in CODEX_LAUNCH_MODES:
                known = ", ".join(sorted(CODEX_LAUNCH_MODES))
                raise HeadRegistryError(f"profile {pid!r} has unknown codex launch mode {mode!r} "
                                        f"(known: {known})")
        fallback = prof.get("fallback") or []
        if not isinstance(fallback, list):
            raise HeadRegistryError(f"profile {pid!r} fallback must be a list, got "
                                    f"{type(fallback).__name__}")
        for fb in fallback:
            fb = _named(fb, f"profile {pid!r} fallback entry")
            if fb not in profiles:
                raise HeadRegistryError(f"profile {pid!r} fallback references unknown profile {fb!r}")


def validate_role_defaults(role_defaults: dict, profiles: dict) -> None:
    """A role routed to a head nobody defined is a routing hole, not a stale line to ignore."""
    if not isinstance(role_defaults, dict):
        raise HeadRegistryError(
            f"[role_defaults] must be a table, got {type(role_defaults).__name__}"
        )
    for role, head in role_defaults.items():
        head = _named(head, f"role {role!r} head")
        if head not in profiles:
            raise HeadRegistryError(f"role {role!r} routes to unknown head {head!r} "
                                    f"(known: {', '.join(sorted(profiles)) or '(none)'})")


def _parse_registry(path: Path) -> dict:
    """The registry document, whichever of its two shapes is on disk.

    A canon is TOML (a human writes it); an installation snapshot is the YAML `secretary upgrade`
    generated from that canon. Both carry the same three tables.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as e:
        raise HeadRegistryError(f"head registry missing: {path}") from e
    except (OSError, UnicodeError) as e:
        raise HeadRegistryError(f"cannot read head registry {path}: {e}") from e
    if path.suffix in {".yaml", ".yml"}:
        try:
            data = yaml.safe_load(text)
        except yaml.YAMLError as e:
            raise HeadRegistryError(f"head registry {path} is not valid YAML: {e}") from e
    else:
        try:
            data = tomllib.loads(text)
        except tomllib.TOMLDecodeError as e:
            raise HeadRegistryError(f"head registry {path} is not valid TOML: {e}") from e
    if not isinstance(data, dict):
        raise HeadRegistryError(f"head registry {path} has an unsupported shape")
    return data


def load_registry(path: Path | None = None) -> Registry:
    """The registry this installation runs off, resolved then parsed. See ``_load_registry``."""
    return _load_registry(path if path is not None else registry_path())


@lru_cache(maxsize=None)
def _load_registry(path: Path) -> Registry:
    """The registry file, parsed and validated. Cached per (process, path) — every dispatcher tick
    is a fresh `python3 -m triggered_agents pipeline tick` process, so this only dedupes the 2+
    reads a single tick already does (claim's `_check_head`, then bring-up's `render_command`),
    never a long-lived process going stale against an edited file on disk. A raised
    HeadRegistryError is not cached — the next call re-reads, so a fixed-then-retried registry
    recovers without a process restart."""
    data = _parse_registry(path)
    resources = data.get("resources") or {}
    profiles = data.get("profiles") or {}
    role_defaults = data.get("role_defaults") or {}
    validate_registry(resources, profiles)
    validate_role_defaults(role_defaults, profiles)
    return Registry(resources=resources, profiles=profiles, role_defaults=role_defaults)


def render_command(profile_id: str, *, role: str, prompt: str, registry: Registry | None = None) -> str:
    """The full shell command for `orca terminal create --command`.

    The role env wrapper sets BOARD_ROLE and the minimal role-specific runtime env before the
    adapter command execs. Secret values stay out of the command string Orca stores.
    """
    reg = registry or load_registry()
    profile = reg.profile(profile_id)
    render = ADAPTERS[profile["adapter"]]
    return role_env.wrap_shell_command(role, render(profile, prompt=prompt))


def render_launch(profile_id: str, *, role: str, prompt: str, workspace: str | None = None,
                  registry: Registry | None = None) -> LaunchSpec:
    """Launch contract for worker/reviewer terminals.

    Most adapters are single-command batch launches. Codex can opt into TUI mode through
    `codex_mode = "tui"` or `TA_CODEX_MODE=tui`: the terminal starts plain `codex`, waits for
    `tui-idle`, then receives `prompt` through `orca terminal send`.
    """
    reg = registry or load_registry()
    profile = reg.profile(profile_id)
    if profile["adapter"] == "codex" and _codex_launch_mode(profile) == "tui":
        return LaunchSpec(
            command=role_env.wrap_shell_command(role, _render_codex_tui(profile, workspace=workspace)),
            initial_prompt=prompt,
            terminal_kind="codex-tui",
        )
    return LaunchSpec(command=render_command(profile_id, role=role, prompt=prompt, registry=reg))


def terminal_kind(profile_id: str, *, registry: Registry | None = None) -> str | None:
    """The tracked Orca terminal kind this profile expects, or None for legacy batch sessions."""
    reg = registry or load_registry()
    profile = reg.profile(profile_id)
    if profile["adapter"] == "codex" and _codex_launch_mode(profile) == "tui":
        return "codex-tui"
    return None
