"""Rendering the front's configuration, hash included, out of the installation's secret store.

The whole site has one authentication boundary. A valid persistent session cookie reaches the
loopback transport directly; otherwise Caddy's basic auth checks the owner's password and the
successful response mints that cookie. Both paths are rendered from the same bcrypt hash, so a
password rotation changes the cookie value too and invalidates every existing browser session.

Nothing about a plaintext credential is stored here. `render` is given the bcrypt hash by its
caller, which reads it from the secret store; the module holds the secret *ids*, which are open
metadata, and the file it produces is written under the data directory, never into the repository.
"""

from __future__ import annotations

import hashlib
import hmac
from dataclasses import dataclass, field
from pathlib import Path

from secretary.web.server import DEFAULT_HOST as DEFAULT_UPSTREAM_HOST
from secretary.web.server import DEFAULT_PORT as DEFAULT_UPSTREAM_PORT
from secretary.web.server import LoopbackOnly, resolve_bind

#: The single account the front knows. Roles and users are a different card; this one has an owner.
USERNAME = "owner"

#: Catalog ids. Open metadata: `secret list` prints these and never the values behind them.
PASSWORD_SECRET_ID = "web-front-password"
HASH_SECRET_ID = "web-front-password-hash"

#: The browser session is a bearer derived from the bcrypt hash, never the password. The `__Host-`
#: prefix makes supporting browsers require Secure, Path=/ and no Domain attribute, which is exactly
#: the shape rendered below. A password rotation produces a new bcrypt hash and therefore a new
#: cookie value without another secret or migration.
SESSION_COOKIE_NAME = "__Host-secretary_front"
SESSION_COOKIE_MAX_AGE = 30 * 24 * 3600
_SESSION_COOKIE_CONTEXT = b"secretary web front session cookie v1"

#: What the owner's browser is told to send the password to. A rendered file names these verbatim.
DEFAULT_SITES: tuple[str, ...] = ()

HEADER = (
    "# Generated by `secretary web-front render`. Do not edit by hand: the next render replaces it.\n"
    "# The password hash below comes from this installation's secret store, which is why this file\n"
    "# is machine state under the data directory and is never a tracked file in the repository.\n"
)


@dataclass(frozen=True)
class FrontConfig:
    """Everything the rendered file says, before it is a file.

    ``bind`` is the rehearsal handle and the rollback handle at once: with it the front listens on
    the addresses named and nothing else, which is how the guard is proved working before a public
    listener exists, and how it is taken off the public interfaces without changing anything else.
    """

    #: Site addresses, as Caddy spells them: `https://name`, `https://1.2.3.4`, `https://[::1]`.
    sites: tuple[str, ...]
    #: The bcrypt hash `basicauth` checks. Never a plaintext password, and never logged.
    password_hash: str
    upstream_host: str = DEFAULT_UPSTREAM_HOST
    upstream_port: int = DEFAULT_UPSTREAM_PORT
    #: Where Caddy keeps its internal CA and the certificates it issues.
    storage: Path | None = None
    #: Interfaces to listen on; empty means every interface the site addresses imply.
    bind: tuple[str, ...] = field(default_factory=tuple)
    username: str = USERNAME


class FrontConfigError(ValueError):
    """The configuration asked for cannot be rendered, and no file was written."""


def session_cookie_value(password_hash: str) -> str:
    """The persistent browser bearer for one rendered password hash.

    The browser never receives the hash. HMAC gives Caddy a fixed value it can match while keeping
    the hash itself on the host, and tying the value to the hash makes `set-password` revoke every
    previously issued browser cookie on the next render/restart.
    """
    return hmac.new(password_hash.encode("utf-8"), _SESSION_COOKIE_CONTEXT, hashlib.sha256).hexdigest()


def render(config: FrontConfig) -> str:
    """The Caddyfile this installation runs, as text."""
    _check(config)
    session = session_cookie_value(config.password_hash)
    lines: list[str] = [HEADER.rstrip("\n"), "", "{"]
    lines.append("\t# No admin API: the front is a proxy with authentication, not a control plane.")
    lines.append("\tadmin off")
    lines.append(
        "\t# The internal CA's root is published for the owner to trust deliberately; a service"
    )
    lines.append("\t# does not get to rewrite this host's trust stores on its own.")
    lines.append("\tskip_install_trust")
    if config.storage is not None:
        lines.append(f"\tstorage file_system {config.storage}")
    lines.append("\t# HTTP/1.1 and HTTP/2 only. HTTP/3 is QUIC over UDP, which this host's firewall")
    lines.append("\t# does not carry; advertising it would buy every visit a failed attempt first.")
    lines.append("\tservers {")
    lines.append("\t\tprotocols h1 h2")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    lines.append(f"{', '.join(config.sites)} {{")
    for address in config.bind:
        lines.append(f"\tbind {address}")
    lines.append("\t# No public name, so no publicly trusted certificate is obtainable: the")
    lines.append("\t# internal CA is the honest option, and OPERATIONS.md says what a browser shows.")
    lines.append("\ttls internal")
    lines.append("")
    lines.append("\t# A browser that authenticated before can present the 30-day bearer. Its value is")
    lines.append("\t# derived from this password hash, so password rotation invalidates it automatically.")
    lines.append(f"\t@owner_session header Cookie *{SESSION_COOKIE_NAME}={session}*")
    lines.append("\thandle @owner_session {")
    lines.append(f"\t\treverse_proxy {_upstream(config)}")
    lines.append("\t}")
    lines.append("")
    lines.append("\t# Without that cookie, keep the existing HTTP Basic challenge. `route` is")
    lines.append("\t# intentional: Caddy normally reorders directives, while the cookie must only be")
    lines.append("\t# minted after Basic Auth has admitted the request, never on its 401 challenge.")
    lines.append("\thandle {")
    lines.append("\t\troute {")
    lines.append("\t\t\tbasicauth {")
    lines.append(f"\t\t\t\t{config.username} {config.password_hash}")
    lines.append("\t\t\t}")
    lines.append(
        f'\t\t\theader +Set-Cookie "{SESSION_COOKIE_NAME}={session}; Path=/; '
        f'Max-Age={SESSION_COOKIE_MAX_AGE}; HttpOnly; Secure; SameSite=Strict"'
    )
    lines.append(f"\t\t\treverse_proxy {_upstream(config)}")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _upstream(config: FrontConfig) -> str:
    host = config.upstream_host
    shown = f"[{host}]" if ":" in host else host
    return f"{shown}:{config.upstream_port}"


def _check(config: FrontConfig) -> None:
    if not config.sites:
        raise FrontConfigError("the front needs at least one site address to answer on")
    for site in config.sites:
        if not site.startswith("https://"):
            raise FrontConfigError(
                f"{site!r} is not an https site address; the front terminates TLS and http is a "
                "redirect Caddy derives from these addresses, never a second way in"
            )
    if not config.password_hash or " " in config.password_hash or "\n" in config.password_hash:
        raise FrontConfigError("the password hash is missing or is not a single bcrypt token")
    if not config.password_hash.startswith("$2"):
        raise FrontConfigError(
            "the password hash is not a bcrypt hash; `caddy hash-password` produces the one "
            "`basicauth` checks"
        )
    if not config.username or any(character.isspace() for character in config.username):
        raise FrontConfigError("the account name must be one word")
    # The same predicate the transport binds by, asked here about where this proxy sends: a front
    # that could forward off the host would be a second, unguarded route into something else.
    try:
        resolve_bind(config.upstream_host)
    except LoopbackOnly as refused:
        raise FrontConfigError(
            f"the front proxies to a loopback address only: {refused}"
        ) from None
    if not 1 <= int(config.upstream_port) <= 65535:
        raise FrontConfigError("the upstream port is not a port")
